# Generated by Django 5.1 on 2024-08-11 12:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(max_length=50, verbose_name="email")),
                ("country", models.CharField(max_length=100, verbose_name="страна")),
                ("city", models.CharField(max_length=100, verbose_name="город")),
                ("street", models.CharField(max_length=250, verbose_name="улица")),
                ("house_number", models.CharField(max_length=50, verbose_name="номер дома")),
                ("name", models.CharField(max_length=100, verbose_name="название")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("factory", "Завод"),
                            ("retailer", "Розничная сеть"),
                            ("enterpriser", "Индивидуальный предприниматель"),
                        ],
                        max_length=60,
                        verbose_name="статус звена сети",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=20, verbose_name="Задолженность перед поставщиком"
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="network.networklink",
                        verbose_name="поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="наименование")),
                ("model", models.CharField(max_length=100, verbose_name="модель")),
                (
                    "release_date",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="дата выхода на рынок"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="product",
                        to="network.networklink",
                        verbose_name="собственник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукция",
            },
        ),
    ]
